# Jenkins Configuration-as-Code for Briklab
jenkins:
  systemMessage: "Briklab - Jenkins"
  numExecutors: 8
  mode: NORMAL
  globalNodeProperties:
    - envVars:
        env:
          - key: NEXUS_DOCKER_USER
            value: "admin"
          - key: NEXUS_DOCKER_PASSWORD
            value: "${NEXUS_ADMIN_PASSWORD}"
          - key: NEXUS_NPM_TOKEN
            value: "${NEXUS_NPM_TOKEN}"
          - key: NEXUS_PYPI_TOKEN
            value: "admin:${NEXUS_ADMIN_PASSWORD}"
          - key: NEXUS_MAVEN_USER
            value: "admin"
          - key: NEXUS_MAVEN_PASSWORD
            value: "${NEXUS_ADMIN_PASSWORD}"
          - key: NEXUS_CARGO_TOKEN
            value: "dummy-dry-run-token"
          - key: NEXUS_NUGET_API_KEY
            value: "admin:${NEXUS_ADMIN_PASSWORD}"
          - key: BRIK_REGISTRY_HOST
            value: "nexus.briklab.test:8082"
          - key: BRIK_REGISTRY_USER
            value: "admin"
          - key: BRIK_REGISTRY_PASSWORD
            value: "${NEXUS_ADMIN_PASSWORD}"
          - key: BRIK_SSH_STRICT_HOST_KEY
            value: "no"
          - key: BRIK_KUBECTL_OPTS
            value: "--insecure-skip-tls-verify --validate=false"
          - key: ARGOCD_SERVER
            value: "host.docker.internal:${ARGOCD_PORT}"
          - key: ARGOCD_AUTH_TOKEN
            value: "${ARGOCD_AUTH_TOKEN}"
          - key: ARGOCD_INSECURE
            value: "true"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: "${JENKINS_ADMIN_PASSWORD:-Brik-Jenkins-2026}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "http://jenkins.briklab.test:9090/"
  globalLibraries:
    libraries:
      - name: "brik"
        defaultVersion: "main"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "http://gitea.briklab.test:3000/brik/brik.git"

tool:
  git:
    installations:
      - name: Default
        home: git

jobs:
  - script: >
      pipelineJob('node-minimal') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-minimal.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-complete') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-complete.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('python-complete') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/python-complete.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('java-complete') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/java-complete.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('rust-complete') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/rust-complete.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('dotnet-complete') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/dotnet-complete.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('python-minimal') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/python-minimal.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('java-minimal') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/java-minimal.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('rust-minimal') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/rust-minimal.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('dotnet-minimal') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/dotnet-minimal.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-full') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-full.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('python-full') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/python-full.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('java-full') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/java-full.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-security') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-security.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-deploy') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-deploy.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-deploy-k8s') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-deploy-k8s.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-deploy-ssh') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-deploy-ssh.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-deploy-gitops') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-deploy-gitops.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-deploy-failure') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-deploy-failure.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-error-build') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-error-build.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('node-error-test') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/node-error-test.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
  - script: >
      pipelineJob('invalid-config') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('http://gitea.briklab.test:3000/brik/invalid-config.git')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
