apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deploy-gitops-rollback
  labels:
    app: node-deploy-gitops-rollback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-deploy-gitops-rollback
  template:
    metadata:
      labels:
        app: node-deploy-gitops-rollback
    spec:
      containers:
        - name: app
          image: nexus.briklab.test:8082/brik/node-deploy-gitops-rollback:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
