#!/usr/bin/env bash
# Generate derived version artifacts from versions.yml (single source of truth).
#
# versions.yml  --(this script)-->  versions.env
#                                    config/jenkins/plugins.txt
#                                    config/brik-images.lock.yaml
#
# Usage:
#   scripts/generate-versions.sh           # regenerate all artifacts
#   scripts/generate-versions.sh --check   # fail if any artifact is stale (CI gate)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BRIKLAB_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SOURCE="${BRIKLAB_ROOT}/versions.yml"
VERSIONS_ENV="${BRIKLAB_ROOT}/versions.env"
PLUGINS_TXT="${BRIKLAB_ROOT}/config/jenkins/plugins.txt"
IMAGES_LOCK="${BRIKLAB_ROOT}/config/brik-images.lock.yaml"

GEN_HEADER="# GENERATED by scripts/generate-versions.sh from versions.yml -- DO NOT EDIT"

command -v yq >/dev/null 2>&1 || { echo "ERROR: yq is required" >&2; exit 1; }
[[ -f "$SOURCE" ]] || { echo "ERROR: $SOURCE not found" >&2; exit 1; }

CHECK=false
[[ "${1:-}" == "--check" ]] && CHECK=true

# --- Renderers (each prints one artifact to stdout) -------------------------

render_versions_env() {
    echo "$GEN_HEADER"
    echo "# Loaded into the shell environment by scripts/lib/common.sh (load_versions)"
    echo "# so docker compose and the setup scripts resolve every version from one place."
    echo ""
    echo "GITLAB_IMAGE=$(yq -r '.infra.gitlab' "$SOURCE")"
    echo "GITLAB_RUNNER_IMAGE=$(yq -r '.infra.gitlab_runner' "$SOURCE")"
    echo "GITLAB_RUNNER_HELPER_IMAGE=$(yq -r '.infra.gitlab_runner_helper' "$SOURCE")"
    echo "GITEA_IMAGE=$(yq -r '.infra.gitea' "$SOURCE")"
    echo "NEXUS_IMAGE=$(yq -r '.infra.nexus' "$SOURCE")"
    echo "JENKINS_BASE_IMAGE=$(yq -r '.infra.jenkins_base' "$SOURCE")"
    echo "SSH_TARGET_BASE_IMAGE=$(yq -r '.infra.ssh_target_base' "$SOURCE")"
    echo "K3S_IMAGE=$(yq -r '.kubernetes.k3s' "$SOURCE")"
    echo "ARGOCD_VERSION=$(yq -r '.kubernetes.argocd' "$SOURCE")"
    echo "YQ_VERSION=$(yq -r '.tools.yq' "$SOURCE")"
}

render_plugins_txt() {
    echo "$GEN_HEADER"
    echo "# Source of truth: versions.yml (jenkins_plugins). Consumed by images/jenkins/Dockerfile."
    yq -r '.jenkins_plugins | to_entries | .[] | .key + ":" + .value' "$SOURCE"
}

render_images_lock() {
    echo "$GEN_HEADER"
    echo "# Source of truth: versions.yml (runner_images). Consumed by scripts/lib/runner-images.sh (briklab.runner_images.pull)."
    echo "# Digest-pinned so a clean rebuild pulls the exact images the E2E suite was validated against."
    echo "# Format: <ref>:<tag>@<digest>. The pull helper fetches the digest and tags it <ref>:<tag> locally."
    echo "images:"
    yq -r '.runner_images[] | "  - " + .ref + ":" + .tag + "@" + .digest' "$SOURCE"
}

# --- Drive: write mode vs check mode ----------------------------------------

artifact_for() {
    case "$1" in
        env)     render_versions_env ;;
        plugins) render_plugins_txt ;;
        lock)    render_images_lock ;;
    esac
}

declare -A TARGETS=( [env]="$VERSIONS_ENV" [plugins]="$PLUGINS_TXT" [lock]="$IMAGES_LOCK" )

if [[ "$CHECK" == "true" ]]; then
    stale=0
    for key in env plugins lock; do
        path="${TARGETS[$key]}"
        if ! diff -q <(artifact_for "$key") "$path" >/dev/null 2>&1; then
            echo "STALE: ${path#"$BRIKLAB_ROOT"/} differs from versions.yml" >&2
            stale=1
        fi
    done
    # Coverage: the runner-image pins must match exactly the tags brik resolves.
    # Best-effort -- skips when brik's registry checkout is not next to briklab.
    # shellcheck source=lib/runner-images.sh
    if BRIKLAB_ROOT="$BRIKLAB_ROOT" source "${SCRIPT_DIR}/lib/runner-images.sh" 2>/dev/null; then
        briklab.runner_images.verify_pins || stale=1
    fi

    if [[ $stale -eq 0 ]]; then
        echo "[OK] All version artifacts are in sync with versions.yml"
    else
        echo "Run: scripts/generate-versions.sh" >&2
        exit 1
    fi
else
    for key in env plugins lock; do
        path="${TARGETS[$key]}"
        artifact_for "$key" > "$path"
        echo "[OK] wrote ${path#"$BRIKLAB_ROOT"/}"
    done
fi
